/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Config.VistaSingleton;
import Utils.FiltroCampos;
import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import javax.swing.text.AbstractDocument;

/**
 *
 * @author ANTHONY-MARTINEZ
 */
public class ManufacturaView extends javax.swing.JFrame {

    /**
     * Creates new form Captura_Linea
     */
    private ManufacturaView() {
        initComponents();
        setLocationRelativeTo(null);
        lbl_codigo_supervisor.setText("<html>Código de<br>Supervisor:</html>");
        lbl_orden_manufactura.setText("<html>Orden de<br>Manufactura:</html>");
        lbl_cantidad_planeada.setText("<html>Cantidad<br>Planeada:</html>");
        btnCorregir.setBackground(Color.BLACK);
        btnRegresar.setBackground(Color.black);
        btnSiguiente.setBackground(Color.black);
        
        ((AbstractDocument) txtCodigoSupervisor.getDocument()).setDocumentFilter(new FiltroCampos.FiltroNumerosYSignoNumeral());
        ((AbstractDocument) txtMogCapturada.getDocument()).setDocumentFilter(new FiltroCampos.FiltroNumerosYLetras());
    }
    
    public static ManufacturaView getInstance() {
        return VistaSingleton.getInstance(ManufacturaView.class);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtSupervisorAsignado = new javax.swing.JTextField();
        lbl_codigo_supervisor = new javax.swing.JLabel();
        txtMogCapturada = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtMog = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtModelo = new javax.swing.JTextField();
        lbl_cantidad_planeada = new javax.swing.JLabel();
        txtCantidadPlaneada = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtDibujo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtParte = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtProceso = new javax.swing.JTextField();
        btnRegresar = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();
        lbl_orden_manufactura = new javax.swing.JLabel();
        txtCodigoSupervisor = new javax.swing.JPasswordField();
        btnCorregir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(800, 1500));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 80)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MAQUINADO");
        jLabel1.setPreferredSize(new java.awt.Dimension(700, 14));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        jLabel2.setText("Supervisor:");

        txtSupervisorAsignado.setEditable(false);
        txtSupervisorAsignado.setBackground(new java.awt.Color(204, 204, 204));
        txtSupervisorAsignado.setFont(new java.awt.Font("Arial", 0, 40)); // NOI18N
        txtSupervisorAsignado.setFocusable(false);

        lbl_codigo_supervisor.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        lbl_codigo_supervisor.setPreferredSize(new java.awt.Dimension(303, 100));

        txtMogCapturada.setEditable(false);
        txtMogCapturada.setBackground(new java.awt.Color(204, 204, 204));
        txtMogCapturada.setFont(new java.awt.Font("Arial", 0, 40)); // NOI18N
        txtMogCapturada.setPreferredSize(new java.awt.Dimension(6, 70));
        txtMogCapturada.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMogCapturadaKeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        jLabel4.setText("MOG:");

        txtMog.setEditable(false);
        txtMog.setBackground(new java.awt.Color(204, 204, 204));
        txtMog.setFont(new java.awt.Font("Arial", 0, 40)); // NOI18N
        txtMog.setFocusable(false);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        jLabel5.setText("Modelo:");

        txtModelo.setEditable(false);
        txtModelo.setBackground(new java.awt.Color(204, 204, 204));
        txtModelo.setFont(new java.awt.Font("Arial", 0, 40)); // NOI18N
        txtModelo.setFocusable(false);

        lbl_cantidad_planeada.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        lbl_cantidad_planeada.setPreferredSize(new java.awt.Dimension(303, 100));

        txtCantidadPlaneada.setEditable(false);
        txtCantidadPlaneada.setBackground(new java.awt.Color(204, 204, 204));
        txtCantidadPlaneada.setFont(new java.awt.Font("Arial", 0, 40)); // NOI18N
        txtCantidadPlaneada.setFocusable(false);

        jLabel7.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        jLabel7.setText("No. Dibujo:");

        txtDibujo.setEditable(false);
        txtDibujo.setBackground(new java.awt.Color(204, 204, 204));
        txtDibujo.setFont(new java.awt.Font("Arial", 0, 40)); // NOI18N
        txtDibujo.setFocusable(false);

        jLabel8.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        jLabel8.setText("No. Parte:");

        txtParte.setEditable(false);
        txtParte.setBackground(new java.awt.Color(204, 204, 204));
        txtParte.setFont(new java.awt.Font("Arial", 0, 40)); // NOI18N
        txtParte.setFocusable(false);

        jLabel9.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        jLabel9.setText("Proceso:");

        txtProceso.setEditable(false);
        txtProceso.setBackground(new java.awt.Color(204, 204, 204));
        txtProceso.setFont(new java.awt.Font("Arial", 0, 40)); // NOI18N
        txtProceso.setFocusable(false);

        btnRegresar.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresar.setText("Regresar");
        btnRegresar.setMaximumSize(new java.awt.Dimension(120, 60));
        btnRegresar.setMinimumSize(new java.awt.Dimension(120, 60));
        btnRegresar.setPreferredSize(new java.awt.Dimension(350, 80));

        btnSiguiente.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        btnSiguiente.setForeground(new java.awt.Color(255, 255, 255));
        btnSiguiente.setText("Siguiente");
        btnSiguiente.setMaximumSize(new java.awt.Dimension(120, 60));
        btnSiguiente.setMinimumSize(new java.awt.Dimension(120, 60));
        btnSiguiente.setPreferredSize(new java.awt.Dimension(120, 80));

        lbl_orden_manufactura.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        lbl_orden_manufactura.setPreferredSize(new java.awt.Dimension(303, 100));

        txtCodigoSupervisor.setBackground(new java.awt.Color(255, 255, 0));
        txtCodigoSupervisor.setFont(new java.awt.Font("Arial", 0, 40)); // NOI18N
        txtCodigoSupervisor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodigoSupervisorKeyTyped(evt);
            }
        });

        btnCorregir.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        btnCorregir.setForeground(new java.awt.Color(255, 255, 255));
        btnCorregir.setText("Corregir datos");
        btnCorregir.setMaximumSize(new java.awt.Dimension(120, 60));
        btnCorregir.setMinimumSize(new java.awt.Dimension(120, 60));
        btnCorregir.setPreferredSize(new java.awt.Dimension(120, 80));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtSupervisorAsignado, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtMog, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtDibujo, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtProceso, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtParte, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_cantidad_planeada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtCantidadPlaneada, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(btnSiguiente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(lbl_codigo_supervisor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtCodigoSupervisor, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(lbl_orden_manufactura, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtMogCapturada, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
                    .addComponent(btnCorregir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_codigo_supervisor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtCodigoSupervisor))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtSupervisorAsignado, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE))
                .addGap(50, 50, 50)
                .addComponent(btnCorregir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtMogCapturada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_orden_manufactura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtMog, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_cantidad_planeada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtCantidadPlaneada))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtDibujo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtParte, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtProceso, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(97, 97, 97))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMogCapturadaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMogCapturadaKeyTyped
        if(txtMogCapturada.getText().length() >= 9)
        {
            evt.consume();
        }
    }//GEN-LAST:event_txtMogCapturadaKeyTyped

    private void txtCodigoSupervisorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoSupervisorKeyTyped
        if(txtCodigoSupervisor.getText().length() >= 12)
        {
            evt.consume();
        }
    }//GEN-LAST:event_txtCodigoSupervisorKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManufacturaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManufacturaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManufacturaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManufacturaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManufacturaView().setVisible(true);
            }
        });
    }

    public JPasswordField getTxtCodigoSupervisor() {
        return txtCodigoSupervisor;
    }

    public void setTxtCodigoSupervisor(JPasswordField txt_codigo_supervisor) {
        this.txtCodigoSupervisor = txt_codigo_supervisor;
    }

    public JTextField getTxtSupervisorAsignado() {
        return txtSupervisorAsignado;
    }

    public void setTxtSupervisorAsignado(JTextField txt_supervisor_asignado) {
        this.txtSupervisorAsignado = txt_supervisor_asignado;
    }

    public JTextField getTxtCantidadPlaneada() {
        return txtCantidadPlaneada;
    }

    public void setTxtCantidadPlaneada(JTextField txt_cantidad_planeada) {
        this.txtCantidadPlaneada = txt_cantidad_planeada;
    }

    public JTextField getTxtModelo() {
        return txtModelo;
    }

    public void setTxtModelo(JTextField txt_descripcion) {
        this.txtModelo = txt_descripcion;
    }

    public JTextField getTxtDibujo() {
        return txtDibujo;
    }

    public void setTxtDibujo(JTextField txt_dibujo) {
        this.txtDibujo = txt_dibujo;
    }

    public JTextField getTxtMog() {
        return txtMog;
    }

    public void setTxtMog(JTextField txt_mog) {
        this.txtMog = txt_mog;
    }

    public JTextField getTxtMogCapturada() {
        return txtMogCapturada;
    }

    public void setTxtMogCapturada(JTextField txt_mog_capturada) {
        this.txtMogCapturada = txt_mog_capturada;
    }

    public JTextField getTxtParte() {
        return txtParte;
    }

    public void setTxtParte(JTextField txt_parte) {
        this.txtParte = txt_parte;
    }

    public JTextField getTxtProceso() {
        return txtProceso;
    }

    public void setTxtProceso(JTextField txt_proceso) {
        this.txtProceso = txt_proceso;
    }

    public JButton getBtnRegresar() {
        return btnRegresar;
    }

    public void setBtnRegresar(JButton btn_regresar) {
        this.btnRegresar = btn_regresar;
    }

    public JButton getBtnSiguiente() {
        return btnSiguiente;
    }

    public void setBtnSiguiente(JButton btn_siguiente) {
        this.btnSiguiente = btn_siguiente;
    }
    
    
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCorregir;
    public javax.swing.JButton btnRegresar;
    public javax.swing.JButton btnSiguiente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_cantidad_planeada;
    private javax.swing.JLabel lbl_codigo_supervisor;
    private javax.swing.JLabel lbl_orden_manufactura;
    public javax.swing.JTextField txtCantidadPlaneada;
    public javax.swing.JPasswordField txtCodigoSupervisor;
    public javax.swing.JTextField txtDibujo;
    public javax.swing.JTextField txtModelo;
    public javax.swing.JTextField txtMog;
    public javax.swing.JTextField txtMogCapturada;
    public javax.swing.JTextField txtParte;
    public javax.swing.JTextField txtProceso;
    public javax.swing.JTextField txtSupervisorAsignado;
    // End of variables declaration//GEN-END:variables
}
