/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Config.VistaSingleton;
import java.awt.Color;

/**
 *
 * @author ANTHONY-MARTINEZ
 */
public class RegistroRBPView extends javax.swing.JFrame {

    /**
     * Creates new form Registro_RBP
     */
    private RegistroRBPView() {
        initComponents();
        setLocationRelativeTo(null);
        lblTituloRBP.setText("<html><center>RBP - REGISTRO DE PIEZAS PRODUCIDAS Y RECHAZADAS</center></html>");
        lblNumeroEmpleado.setText("<html>Número<br>empleado:</html>");
        lblEmpleado.setText("<html>Nombre<br>empleado:</html>");
        lblTurno.setText("<html><center>Turno<br>trabajado:</center></html>");
        lblHoraInicio.setText("<html><center>Hora<br>inicio:</center></html>");
        lblPiezasRecibidas.setText("<html><center>Piezas<br>recibidas:</center></html>");
        lblScrapTotal.setText("<html><center>Scrap<br>total:</center></html>");
        btnDibujo.setText("<html><center>Ver<br>Dibujo</center></html>");
        lblPiezasxFila.setText("<html><center>Piezas<br>por fila</center></html>");
        lblFilasCompletas.setText("<html><center>Filas<br>completas</center></html>");
        lblNivelesCompletos.setText("<html><center>Niveles<br>completos</center></html>");
        btnRegresar.setBackground(Color.BLACK);
        btnSiguiente.setBackground(Color.BLACK);
        btnDAS.setBackground(Color.BLACK);
        btnParoLinea.setBackground(Color.RED);
        btnCambioMOG.setBackground(Color.BLACK);
        btnParoLinea.setText("<html><center>Paro<br>de Línea</center></html>");
        btnCambioMOG.setText("<html><center>Cambio<br>de MOG</center></html>");
    }
    
    public static RegistroRBPView getInstance() {
        return VistaSingleton.getInstance(RegistroRBPView.class);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        lblNumeroEmpleado = new javax.swing.JLabel();
        lblEmpleado = new javax.swing.JLabel();
        lblTurno = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        lblPiezasRecibidas = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        lblHoraInicio = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        lblTituloRBP = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        btnDibujo = new javax.swing.JButton();
        jLabelCanastasCom = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        lblScrapTotal = new javax.swing.JLabel();
        jTextFieldRSW1 = new javax.swing.JTextField();
        lblPiezasxFila = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldFSW1 = new javax.swing.JTextField();
        jTextFieldCSW1 = new javax.swing.JTextField();
        jLabel212 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldCantSW1 = new javax.swing.JTextField();
        jLabelCanastasCom1 = new javax.swing.JLabel();
        jTextFieldFSW2 = new javax.swing.JTextField();
        lblFilasCompletas = new javax.swing.JLabel();
        lblNivelesCompletos = new javax.swing.JLabel();
        jTextFieldCSW2 = new javax.swing.JTextField();
        jTextFieldCantSW2 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();
        btnDAS = new javax.swing.JButton();
        btnParoLinea = new javax.swing.JButton();
        btnCambioMOG = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(800, 1500));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jLabel3.setText("Fecha:");

        jTextField1.setBackground(new java.awt.Color(255, 255, 0));
        jTextField1.setFont(new java.awt.Font("Arial", 0, 40)); // NOI18N

        lblNumeroEmpleado.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N

        lblEmpleado.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N

        lblTurno.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        lblTurno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jTextField3.setEditable(false);
        jTextField3.setBackground(new java.awt.Color(204, 204, 204));
        jTextField3.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N

        jTextField4.setEditable(false);
        jTextField4.setBackground(new java.awt.Color(204, 204, 204));
        jTextField4.setFont(new java.awt.Font("Arial", 0, 40)); // NOI18N

        lblPiezasRecibidas.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        lblPiezasRecibidas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jTextField7.setEditable(false);
        jTextField7.setBackground(new java.awt.Color(204, 204, 204));
        jTextField7.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N

        lblHoraInicio.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        lblHoraInicio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jTextField5.setEditable(false);
        jTextField5.setBackground(new java.awt.Color(204, 204, 204));
        jTextField5.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N

        lblTituloRBP.setFont(new java.awt.Font("Arial", 1, 44)); // NOI18N
        lblTituloRBP.setForeground(new java.awt.Color(0, 102, 0));
        lblTituloRBP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jTextField6.setEditable(false);
        jTextField6.setBackground(new java.awt.Color(204, 204, 204));
        jTextField6.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N

        btnDibujo.setBackground(new java.awt.Color(0, 0, 0));
        btnDibujo.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        btnDibujo.setForeground(new java.awt.Color(255, 255, 255));

        jLabelCanastasCom.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jLabelCanastasCom.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCanastasCom.setText("Canastas Completas");
        jLabelCanastasCom.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTextField8.setEditable(false);
        jTextField8.setBackground(new java.awt.Color(204, 204, 204));
        jTextField8.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N

        lblScrapTotal.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        lblScrapTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jTextFieldRSW1.setEditable(false);
        jTextFieldRSW1.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldRSW1.setFont(new java.awt.Font("Arial", 0, 40)); // NOI18N
        jTextFieldRSW1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldRSW1.setFocusable(false);

        lblPiezasxFila.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        lblPiezasxFila.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel9.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Filas");
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jTextFieldFSW1.setEditable(false);
        jTextFieldFSW1.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldFSW1.setFont(new java.awt.Font("Arial", 0, 40)); // NOI18N
        jTextFieldFSW1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldFSW1.setFocusable(false);

        jTextFieldCSW1.setEditable(false);
        jTextFieldCSW1.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldCSW1.setFont(new java.awt.Font("Arial", 0, 40)); // NOI18N
        jTextFieldCSW1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldCSW1.setFocusable(false);

        jLabel212.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jLabel212.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel212.setText("Niveles");

        jLabel11.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Canastas");

        jTextFieldCantSW1.setEditable(false);
        jTextFieldCantSW1.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldCantSW1.setFont(new java.awt.Font("Arial", 0, 40)); // NOI18N
        jTextFieldCantSW1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldCantSW1.setFocusable(false);

        jLabelCanastasCom1.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jLabelCanastasCom1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCanastasCom1.setText("Canastas Incompletas");
        jLabelCanastasCom1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTextFieldFSW2.setEditable(false);
        jTextFieldFSW2.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldFSW2.setFont(new java.awt.Font("Arial", 0, 40)); // NOI18N
        jTextFieldFSW2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldFSW2.setFocusable(false);

        lblFilasCompletas.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        lblFilasCompletas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFilasCompletas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblNivelesCompletos.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        lblNivelesCompletos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jTextFieldCSW2.setEditable(false);
        jTextFieldCSW2.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldCSW2.setFont(new java.awt.Font("Arial", 0, 40)); // NOI18N
        jTextFieldCSW2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldCSW2.setFocusable(false);

        jTextFieldCantSW2.setEditable(false);
        jTextFieldCantSW2.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldCantSW2.setFont(new java.awt.Font("Arial", 0, 40)); // NOI18N
        jTextFieldCantSW2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldCantSW2.setFocusable(false);

        jLabel12.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Sobrante");

        btnRegresar.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresar.setText("Regresar");
        btnRegresar.setMaximumSize(new java.awt.Dimension(120, 60));
        btnRegresar.setMinimumSize(new java.awt.Dimension(120, 60));
        btnRegresar.setPreferredSize(new java.awt.Dimension(350, 80));

        btnSiguiente.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        btnSiguiente.setForeground(new java.awt.Color(255, 255, 255));
        btnSiguiente.setText("Siguiente");
        btnSiguiente.setMaximumSize(new java.awt.Dimension(120, 60));
        btnSiguiente.setMinimumSize(new java.awt.Dimension(120, 60));
        btnSiguiente.setPreferredSize(new java.awt.Dimension(120, 80));

        btnDAS.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        btnDAS.setForeground(new java.awt.Color(255, 255, 255));
        btnDAS.setText("DAS");
        btnDAS.setMaximumSize(new java.awt.Dimension(120, 60));
        btnDAS.setMinimumSize(new java.awt.Dimension(120, 60));
        btnDAS.setPreferredSize(new java.awt.Dimension(350, 80));
        btnDAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDASActionPerformed(evt);
            }
        });

        btnParoLinea.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        btnParoLinea.setForeground(new java.awt.Color(255, 255, 255));
        btnParoLinea.setText("PARO DE LÍNEA");
        btnParoLinea.setMaximumSize(new java.awt.Dimension(120, 60));
        btnParoLinea.setMinimumSize(new java.awt.Dimension(120, 60));
        btnParoLinea.setPreferredSize(new java.awt.Dimension(350, 80));

        btnCambioMOG.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        btnCambioMOG.setForeground(new java.awt.Color(255, 255, 255));
        btnCambioMOG.setText("Cambio de MOG");
        btnCambioMOG.setMaximumSize(new java.awt.Dimension(120, 60));
        btnCambioMOG.setMinimumSize(new java.awt.Dimension(120, 60));
        btnCambioMOG.setPreferredSize(new java.awt.Dimension(350, 80));
        btnCambioMOG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambioMOGActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTituloRBP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                            .addComponent(lblNumeroEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                                .addComponent(jTextField4, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addGap(51, 51, 51)
                        .addComponent(btnDibujo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTurno))
                        .addGap(60, 60, 60)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblHoraInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField5, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                        .addGap(70, 70, 70)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblPiezasRecibidas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField7, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                        .addGap(70, 70, 70)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(lblScrapTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldRSW1)
                            .addComponent(lblPiezasxFila, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(60, 60, 60)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldFSW1, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(jTextFieldCSW1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(jLabel212, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(70, 70, 70)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(jTextFieldCantSW1)))
                    .addComponent(jLabelCanastasCom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelCanastasCom1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextFieldFSW2)
                                .addGap(65, 65, 65)
                                .addComponent(jTextFieldCSW2)
                                .addGap(65, 65, 65)
                                .addComponent(jTextFieldCantSW2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblFilasCompletas, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(65, 65, 65)
                                .addComponent(lblNivelesCompletos, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(65, 65, 65)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnCambioMOG, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(btnParoLinea, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(btnDAS, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(lblTituloRBP)
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField6, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField1)
                            .addComponent(lblNumeroEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                            .addComponent(lblEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(btnDibujo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblHoraInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblPiezasRecibidas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblScrapTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lblTurno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(jLabelCanastasCom)
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel212, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPiezasxFila, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldRSW1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldFSW1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCSW1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCantSW1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(jLabelCanastasCom1)
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblNivelesCompletos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(lblFilasCompletas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextFieldCSW2, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                            .addComponent(jTextFieldCantSW2)
                            .addComponent(jTextFieldFSW2)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnDAS, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(btnParoLinea, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15)
                .addComponent(btnCambioMOG, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 328, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDASActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDASActionPerformed

    private void btnCambioMOGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambioMOGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCambioMOGActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroRBPView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroRBPView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroRBPView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroRBPView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroRBPView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCambioMOG;
    public javax.swing.JButton btnDAS;
    public javax.swing.JButton btnDibujo;
    public javax.swing.JButton btnParoLinea;
    public javax.swing.JButton btnRegresar;
    public javax.swing.JButton btnSiguiente;
    public javax.swing.JLabel jLabel11;
    public javax.swing.JLabel jLabel12;
    public javax.swing.JLabel jLabel212;
    private javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel9;
    public javax.swing.JLabel jLabelCanastasCom;
    public javax.swing.JLabel jLabelCanastasCom1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    public javax.swing.JTextField jTextFieldCSW1;
    public javax.swing.JTextField jTextFieldCSW2;
    public javax.swing.JTextField jTextFieldCantSW1;
    public javax.swing.JTextField jTextFieldCantSW2;
    public javax.swing.JTextField jTextFieldFSW1;
    public javax.swing.JTextField jTextFieldFSW2;
    public javax.swing.JTextField jTextFieldRSW1;
    private javax.swing.JLabel lblEmpleado;
    public javax.swing.JLabel lblFilasCompletas;
    private javax.swing.JLabel lblHoraInicio;
    public javax.swing.JLabel lblNivelesCompletos;
    private javax.swing.JLabel lblNumeroEmpleado;
    private javax.swing.JLabel lblPiezasRecibidas;
    public javax.swing.JLabel lblPiezasxFila;
    private javax.swing.JLabel lblScrapTotal;
    public javax.swing.JLabel lblTituloRBP;
    private javax.swing.JLabel lblTurno;
    // End of variables declaration//GEN-END:variables
}
