/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Config.VistaSingleton;
import Utils.FiltroCampos;
import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JTextField;
import javax.swing.text.AbstractDocument;

/**
 *
 * @author ANTHONY-MARTINEZ
 */
public class ValidarLineaView extends javax.swing.JFrame {

    /**
     * Creates new form Autenticacion
     */
    private ValidarLineaView() {
        initComponents();
        setLocationRelativeTo(null);
        btnSalir.setBackground(Color.black);
        
        ((AbstractDocument) txtLineaProduccion.getDocument()).setDocumentFilter(new FiltroCampos.FiltroNumerosYLetras());
    }
    
    public static ValidarLineaView getInstance() {
        return VistaSingleton.getInstance(ValidarLineaView.class);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_bienvenido = new javax.swing.JLabel();
        lbl_codigo_supervisor = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        txtLineaProduccion = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 1600));
        setResizable(false);

        jPanel1.setPreferredSize(new java.awt.Dimension(800, 1500));

        lbl_bienvenido.setFont(new java.awt.Font("Arial", 1, 80)); // NOI18N
        lbl_bienvenido.setForeground(new java.awt.Color(0, 102, 0));
        lbl_bienvenido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_bienvenido.setText("MAQUINADO");
        lbl_bienvenido.setPreferredSize(new java.awt.Dimension(700, 50));

        lbl_codigo_supervisor.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        lbl_codigo_supervisor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_codigo_supervisor.setText("Línea de producción");
        lbl_codigo_supervisor.setPreferredSize(new java.awt.Dimension(700, 50));

        btnSalir.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("Salir");
        btnSalir.setPreferredSize(new java.awt.Dimension(700, 70));

        txtLineaProduccion.setBackground(new java.awt.Color(255, 255, 0));
        txtLineaProduccion.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        txtLineaProduccion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtLineaProduccion.setPreferredSize(new java.awt.Dimension(6, 70));
        txtLineaProduccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLineaProduccionKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_bienvenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_codigo_supervisor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtLineaProduccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(50, 50, 50))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(300, 300, 300)
                .addComponent(lbl_bienvenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(57, 57, 57)
                .addComponent(lbl_codigo_supervisor, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(txtLineaProduccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(134, 134, 134)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(800, 800, 800))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtLineaProduccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLineaProduccionKeyTyped
        if(txtLineaProduccion.getText().length() >= 4)
        {
            evt.consume();
        }
    }//GEN-LAST:event_txtLineaProduccionKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CambioMOGView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CambioMOGView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CambioMOGView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CambioMOGView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ValidarLineaView().setVisible(true);
            }
        });
    }

    public JButton getBtnIngresar() {
        return btnSalir;
    }

    public void setBtnIngresar(JButton btn_ingresar) {
        this.btnSalir = btn_ingresar;
    }

    public JButton getBtnSalir() {
        return btnSalir;
    }

    public void setBtnSalir(JButton btn_salir) {
        this.btnSalir = btn_salir;
    }

    public JTextField getTxtLineaProduccion() {
        return txtLineaProduccion;
    }

    public void setTxtLineaProduccion(JTextField txt_linea_produccion) {
        this.txtLineaProduccion = txt_linea_produccion;
    }
    
    
    
    
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnSalir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_bienvenido;
    private javax.swing.JLabel lbl_codigo_supervisor;
    private javax.swing.JTextField txtLineaProduccion;
    // End of variables declaration//GEN-END:variables
}
