/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;
import Model.Global;
import javax.swing.*;  
import javax.swing.table.TableColumn;
/**
 *
 * @author DMM-ADMIN
 */
public class PreviewsMaquinadoDAS extends javax.swing.JFrame {

    /**
     * Creates new form DASEmpaqueMesas
     */
    public PreviewsMaquinadoDAS() {
        initComponents();
        //Los label de turno son para colocar en la preview que turno fue el que se lleno del DAS
        jLabelturnouno.setText("<html><body align=\"center\">1er. Turno</body></html>");
        jLabelturnodos.setText("<html><body align=\"center\">2do. Turno</body></html>");
        jLabelturnotres.setText("<html><body align=\"center\">3er. Turno</body></html>");
        //Labels para la tabla de total de producción
        jLabel15.setText("<html><body align=\"center\">Cantidad de piezas<br>(Meta)</body></html>");
        jLabel11.setText("<html><body align=\"center\">Cantidad Piezas<br>Procesadas</body></html>");
        jLabel16.setText("<html><body align=\"center\">Cantidad Piezas<br>Buenas</body></html>");
        jLabel18.setText("<html><body align=\"center\">Cantidad Piezas<br>Rechazadas</body></html>");
        jLabel20.setText("<html><body align=\"center\">% de<br>Desempeño</body></html>");
        
       ////////////////////////////////////////////tablas/////////////////////////////////////////////////////
        jTableProduccion.getColumnModel().getColumn(0).setHeaderValue("<html><body align=\"center\">No. MOG</body></html>");
        jTableProduccion.getColumnModel().getColumn(1).setHeaderValue("<html><body align=\"center\">Modelo</body></html>");
        jTableProduccion.getColumnModel().getColumn(2).setHeaderValue("<html><body align=\"center\">STD</body></html>");
        jTableProduccion.getColumnModel().getColumn(3).setHeaderValue("<html><body align=\"center\">Lote</body></html>");
        
       
        jTableProduccion.getColumnModel().getColumn(0).setPreferredWidth(80);
        jTableProduccion.getColumnModel().getColumn(1).setPreferredWidth(80);
        jTableProduccion.getColumnModel().getColumn(2).setPreferredWidth(40);
        jTableProduccion.getColumnModel().getColumn(3).setPreferredWidth(40);

        
        jTableProduccion.setRowHeight(0, 30);
        jTableProduccion.setRowHeight(1, 30);
        jTableProduccion.setRowHeight(2, 30);
        jTableProduccion.setRowHeight(3, 30);


        
        
        //jTableCausaParo.getColumnModel().getColumn(0).setPreferredWidth(10);
        //7///jTableCausaParo.getColumnModel().getColumn(1).setPreferredWidth(10);
       // j//TableCausaParo.getColumnModel().getColumn(2).setPreferredWidth(120);
        
        //jTextFieldOperador.setEditable(false);
        //jTextFieldVerifica.setEditable(false);
         
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabelGrupo3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelDia = new javax.swing.JLabel();
        jLabelMes = new javax.swing.JLabel();
        jLabelAnio = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabelCantProcesada = new javax.swing.JLabel();
        jLabelMeta = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabelPiezasBuenas = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabelRechaSort = new javax.swing.JLabel();
        jLabelSobranteF = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProduccion = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jButtonAtrasDAS = new javax.swing.JButton();
        jButtonSiguienteDAS = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabelLineaDAS = new javax.swing.JLabel();
        jLabelGrupo1 = new javax.swing.JLabel();
        jLabelGrupo2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        jLayeredPane4 = new javax.swing.JLayeredPane();
        jLabelturnotres = new javax.swing.JLabel();
        jLabelturnouno = new javax.swing.JLabel();
        jLabelturnodos = new javax.swing.JLabel();
        jLayeredPane5 = new javax.swing.JLayeredPane();
        jLayeredPane7 = new javax.swing.JLayeredPane();
        jLayeredPane8 = new javax.swing.JLayeredPane();
        jLayeredPane9 = new javax.swing.JLayeredPane();
        jLabel14 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jTextFieldSoporteRapido = new javax.swing.JTextField();
        jTextFieldOperador = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTablePiezasHora = new javax.swing.JTable();
        jLayeredPane10 = new javax.swing.JLayeredPane();
        jLayeredPane11 = new javax.swing.JLayeredPane();
        jLabel75 = new javax.swing.JLabel();
        jTextFieldInspector = new javax.swing.JTextField();
        jTextFieldtototalacumulado = new javax.swing.JTextField();
        jTextFieldtotalpzas = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableParosLinea = new javax.swing.JTable();
        jLabel81 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableProduccionPiezas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 1600));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Arial", 0, 44)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 0));
        jLabel6.setText("ACTIVIDAD DIARIA \"MAQUINADO\"");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 720, 80));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Línea");
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 70, 30));

        jLabelGrupo3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabelGrupo3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelGrupo3.setText("3");
        jLabelGrupo3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabelGrupo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, 80, 50));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Día");
        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 90, 90, 30));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Mes");
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 90, 90, 30));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Año");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 90, 90, 30));

        jLabelDia.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabelDia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabelDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 120, 90, 50));

        jLabelMes.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabelMes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabelMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 120, 90, 50));

        jLabelAnio.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabelAnio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAnio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabelAnio, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 120, 90, 50));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Totales de Producción ");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 420, 700, -1));

        jLabel11.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 440, 140, 50));

        jLabelCantProcesada.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabelCantProcesada.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCantProcesada.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabelCantProcesada, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 490, 140, 40));

        jLabelMeta.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabelMeta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMeta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabelMeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 490, 140, 40));

        jLabel15.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Cantidad de piezas (Meta)");
        jLabel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 440, 140, 50));

        jLabel16.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 440, 140, 50));

        jLabelPiezasBuenas.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabelPiezasBuenas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPiezasBuenas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabelPiezasBuenas, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 490, 140, 40));

        jLabel18.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 440, 140, 50));

        jLabelRechaSort.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabelRechaSort.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelRechaSort.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabelRechaSort, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 490, 140, 40));

        jLabelSobranteF.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabelSobranteF.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSobranteF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabelSobranteF, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 490, 140, 40));

        jLabel20.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 440, 140, 50));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Registro de Producción");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 580, 830, 30));

        jTableProduccion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No. MOG", "Modelo", "STD", "Lote"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableProduccion);
        if (jTableProduccion.getColumnModel().getColumnCount() > 0) {
            jTableProduccion.getColumnModel().getColumn(0).setResizable(false);
            jTableProduccion.getColumnModel().getColumn(0).setPreferredWidth(100);
            jTableProduccion.getColumnModel().getColumn(0).setHeaderValue("No. MOG");
            jTableProduccion.getColumnModel().getColumn(1).setResizable(false);
            jTableProduccion.getColumnModel().getColumn(1).setPreferredWidth(100);
            jTableProduccion.getColumnModel().getColumn(1).setHeaderValue("Modelo");
            jTableProduccion.getColumnModel().getColumn(2).setResizable(false);
            jTableProduccion.getColumnModel().getColumn(2).setPreferredWidth(40);
            jTableProduccion.getColumnModel().getColumn(2).setHeaderValue("STD");
            jTableProduccion.getColumnModel().getColumn(3).setResizable(false);
            jTableProduccion.getColumnModel().getColumn(3).setPreferredWidth(40);
            jTableProduccion.getColumnModel().getColumn(3).setHeaderValue("Lote");
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 620, 320, 140));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Registro de piezas por hora");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 780, 840, -1));

        jButtonAtrasDAS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/atras.png"))); // NOI18N
        jButtonAtrasDAS.setBorderPainted(false);
        jButtonAtrasDAS.setContentAreaFilled(false);
        getContentPane().add(jButtonAtrasDAS, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 1490, 260, 80));

        jButtonSiguienteDAS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/siguente.png"))); // NOI18N
        jButtonSiguienteDAS.setToolTipText("");
        jButtonSiguienteDAS.setBorderPainted(false);
        jButtonSiguienteDAS.setContentAreaFilled(false);
        getContentPane().add(jButtonSiguienteDAS, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 1490, 260, 80));

        jLabel2.setText(Global.VERSION);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 10, 70, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Grupo");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 240, 30));

        jLabelLineaDAS.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabelLineaDAS.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelLineaDAS.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabelLineaDAS, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 70, 50));

        jLabelGrupo1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabelGrupo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelGrupo1.setText("1");
        jLabelGrupo1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabelGrupo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 80, 50));

        jLabelGrupo2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabelGrupo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelGrupo2.setText("2");
        jLabelGrupo2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabelGrupo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 80, 50));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Circular el Turno Trabajado");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 480, 30));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));
        getContentPane().add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 100, 90));
        getContentPane().add(jLayeredPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 140, 80));
        getContentPane().add(jLayeredPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 90, 140, 80));
        getContentPane().add(jLayeredPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 210, 80));

        jLabelturnotres.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabelturnotres.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelturnotres.setText("3er Turno");
        jLabelturnotres.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabelturnotres, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 230, 160, 30));

        jLabelturnouno.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabelturnouno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelturnouno.setText("1er Turno");
        jLabelturnouno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabelturnouno, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 160, 30));

        jLabelturnodos.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabelturnodos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelturnodos.setText("2do Turno");
        jLabelturnodos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabelturnodos, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 230, 160, 30));
        getContentPane().add(jLayeredPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 200, 210, 80));
        getContentPane().add(jLayeredPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 440, 100, 90));
        getContentPane().add(jLayeredPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 300, 30, 90));
        getContentPane().add(jLayeredPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 620, 30, 90));

        jLabel14.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Nombre Inspector");
        jLabel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 300, 280, 50));

        jLabel17.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Nombre Soporte Rápido");
        jLabel17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 280, 50));

        jLabel19.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Nombre Operador");
        jLabel19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, 280, 50));

        jTextFieldSoporteRapido.setEditable(false);
        jTextFieldSoporteRapido.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTextFieldSoporteRapido.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldSoporteRapido.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextFieldSoporteRapido.setDisabledTextColor(new java.awt.Color(240, 240, 240));
        jTextFieldSoporteRapido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSoporteRapidoActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldSoporteRapido, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 280, 40));

        jTextFieldOperador.setEditable(false);
        jTextFieldOperador.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTextFieldOperador.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldOperador.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextFieldOperador.setDisabledTextColor(new java.awt.Color(240, 240, 240));
        getContentPane().add(jTextFieldOperador, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 350, 280, 40));

        jTablePiezasHora.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTablePiezasHora.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Hora", "Pieza por hora", "Acumulado", "OkNg", "Nombre"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTablePiezasHora);
        if (jTablePiezasHora.getColumnModel().getColumnCount() > 0) {
            jTablePiezasHora.getColumnModel().getColumn(0).setResizable(false);
            jTablePiezasHora.getColumnModel().getColumn(0).setPreferredWidth(10);
            jTablePiezasHora.getColumnModel().getColumn(1).setResizable(false);
            jTablePiezasHora.getColumnModel().getColumn(1).setPreferredWidth(5);
            jTablePiezasHora.getColumnModel().getColumn(2).setResizable(false);
            jTablePiezasHora.getColumnModel().getColumn(2).setPreferredWidth(10);
            jTablePiezasHora.getColumnModel().getColumn(3).setResizable(false);
            jTablePiezasHora.getColumnModel().getColumn(3).setPreferredWidth(5);
            jTablePiezasHora.getColumnModel().getColumn(4).setResizable(false);
            jTablePiezasHora.getColumnModel().getColumn(4).setPreferredWidth(200);
        }

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 820, 840, 170));
        getContentPane().add(jLayeredPane10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 30, 90));
        getContentPane().add(jLayeredPane11, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 670, 30, 20));

        jLabel75.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel75.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel75.setText("Total");
        jLabel75.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel75, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 990, 130, 30));

        jTextFieldInspector.setEditable(false);
        jTextFieldInspector.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTextFieldInspector.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldInspector.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextFieldInspector.setDisabledTextColor(new java.awt.Color(240, 240, 240));
        getContentPane().add(jTextFieldInspector, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 350, 280, 40));

        jTextFieldtototalacumulado.setEditable(false);
        jTextFieldtototalacumulado.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTextFieldtototalacumulado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldtototalacumulado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextFieldtototalacumulado.setDisabledTextColor(new java.awt.Color(240, 240, 240));
        getContentPane().add(jTextFieldtototalacumulado, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 990, 130, 30));

        jTextFieldtotalpzas.setEditable(false);
        jTextFieldtotalpzas.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTextFieldtotalpzas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldtotalpzas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextFieldtotalpzas.setDisabledTextColor(new java.awt.Color(240, 240, 240));
        getContentPane().add(jTextFieldtotalpzas, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 990, 130, 30));

        jTableParosLinea.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTableParosLinea.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Hora Inicio", "Hora Fin", "Tiempo", "No. Causa", "Detalle"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTableParosLinea);
        if (jTableParosLinea.getColumnModel().getColumnCount() > 0) {
            jTableParosLinea.getColumnModel().getColumn(0).setResizable(false);
            jTableParosLinea.getColumnModel().getColumn(1).setResizable(false);
            jTableParosLinea.getColumnModel().getColumn(2).setResizable(false);
            jTableParosLinea.getColumnModel().getColumn(3).setResizable(false);
            jTableParosLinea.getColumnModel().getColumn(4).setResizable(false);
        }

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1090, 840, 250));

        jLabel81.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel81.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel81.setText("Causas de paro en proceso (Si la inactividad es mayor a 5 min, favor de registrar en la siguiente tabla)");
        getContentPane().add(jLabel81, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1060, 840, -1));

        jTableProduccionPiezas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Inicio", "Fin", "Inicio P", "Fin P", "Piezas Procezadas", "Piezas Buenas", "Piezas Rechazadas"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTableProduccionPiezas);
        if (jTableProduccionPiezas.getColumnModel().getColumnCount() > 0) {
            jTableProduccionPiezas.getColumnModel().getColumn(0).setResizable(false);
            jTableProduccionPiezas.getColumnModel().getColumn(0).setPreferredWidth(40);
            jTableProduccionPiezas.getColumnModel().getColumn(1).setResizable(false);
            jTableProduccionPiezas.getColumnModel().getColumn(1).setPreferredWidth(40);
            jTableProduccionPiezas.getColumnModel().getColumn(2).setResizable(false);
            jTableProduccionPiezas.getColumnModel().getColumn(2).setPreferredWidth(40);
            jTableProduccionPiezas.getColumnModel().getColumn(3).setResizable(false);
            jTableProduccionPiezas.getColumnModel().getColumn(3).setPreferredWidth(40);
            jTableProduccionPiezas.getColumnModel().getColumn(4).setResizable(false);
            jTableProduccionPiezas.getColumnModel().getColumn(4).setPreferredWidth(100);
            jTableProduccionPiezas.getColumnModel().getColumn(5).setResizable(false);
            jTableProduccionPiezas.getColumnModel().getColumn(5).setPreferredWidth(100);
            jTableProduccionPiezas.getColumnModel().getColumn(6).setResizable(false);
            jTableProduccionPiezas.getColumnModel().getColumn(6).setPreferredWidth(100);
        }

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 620, 520, 140));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldSoporteRapidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSoporteRapidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSoporteRapidoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PreviewsMaquinadoDAS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PreviewsMaquinadoDAS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PreviewsMaquinadoDAS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PreviewsMaquinadoDAS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PreviewsMaquinadoDAS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonAtrasDAS;
    public javax.swing.JButton jButtonSiguienteDAS;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JLabel jLabelAnio;
    public javax.swing.JLabel jLabelCantProcesada;
    public javax.swing.JLabel jLabelDia;
    public javax.swing.JLabel jLabelGrupo1;
    public javax.swing.JLabel jLabelGrupo2;
    public javax.swing.JLabel jLabelGrupo3;
    public javax.swing.JLabel jLabelLineaDAS;
    public javax.swing.JLabel jLabelMes;
    public javax.swing.JLabel jLabelMeta;
    public javax.swing.JLabel jLabelPiezasBuenas;
    public javax.swing.JLabel jLabelRechaSort;
    public javax.swing.JLabel jLabelSobranteF;
    public javax.swing.JLabel jLabelturnodos;
    public javax.swing.JLabel jLabelturnotres;
    public javax.swing.JLabel jLabelturnouno;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane10;
    private javax.swing.JLayeredPane jLayeredPane11;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JLayeredPane jLayeredPane4;
    private javax.swing.JLayeredPane jLayeredPane5;
    private javax.swing.JLayeredPane jLayeredPane7;
    private javax.swing.JLayeredPane jLayeredPane8;
    private javax.swing.JLayeredPane jLayeredPane9;
    public javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JTable jTableParosLinea;
    public javax.swing.JTable jTablePiezasHora;
    public javax.swing.JTable jTableProduccion;
    public javax.swing.JTable jTableProduccionPiezas;
    public javax.swing.JTextField jTextFieldInspector;
    public javax.swing.JTextField jTextFieldOperador;
    public javax.swing.JTextField jTextFieldSoporteRapido;
    public javax.swing.JTextField jTextFieldtotalpzas;
    public javax.swing.JTextField jTextFieldtototalacumulado;
    // End of variables declaration//GEN-END:variables
}
