/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javax.swing.JTextField;
import Model.Global;
/**
 *
 * @author Lares
 */
public class Second_windowRBP extends javax.swing.JFrame {

    /**
     * Creates new form First_window
     */
    public Second_windowRBP() {
        initComponents();
        ((JTextField) this.jDateChooserDateSW.getDateEditor()).setEditable(false);  
        jDateChooserDateSW.getCalendarButton().setEnabled(false);
        jTextFieldSobraInicial.setEditable(false);
        jTextFieldSobraInicial.setText("0");
        jLabel2.setText("<html><body align=\"center\">Número de<br>nombre</body></html>");
        jLabel12.setText("<html><body align=\"center\">Niveles<br>completos</body></html>");
        jLabel14.setText("<html><body align=\"center\">Filas<br>completas</body></html>");
        jLabel10.setText("<html><body align=\"center\">Sobrante<br>inicial</body></html>");
        jLabel2.setText("<html><body align=\"center\">Número de<br>empleado</body></html>");
        jLabel13.setText("<html><body align=\"center\">Piezas por<br>fila</body></html>");
        jLabel16.setText("<html><body align=\"center\">Piezas por<br>fila</body></html>");
        jTextFieldTPiecesSW.setEditable(false);
        jTextFieldEndSW.setEditable(false);
        jTextFieldTotalSW.setEditable(false);
        jTextFieldNameSW.setEditable(false);
        jTextFieldStartSW.setEditable(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabelTotal_Hours = new javax.swing.JLabel();
        jLabelPiezasxfila = new javax.swing.JLabel();
        jTextFieldCantSW1 = new javax.swing.JTextField();
        jTextFieldRSW1 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jTextFieldTPiecesSW = new javax.swing.JTextField();
        jTextFieldStartSW = new javax.swing.JTextField();
        jTextFieldEndSW = new javax.swing.JTextField();
        jTextFieldTotalSW = new javax.swing.JTextField();
        jDateChooserDateSW = new com.toedter.calendar.JDateChooser();
        jTextFieldFSW1 = new javax.swing.JTextField();
        jTextFieldCSW1 = new javax.swing.JTextField();
        jTextFieldRSW2 = new javax.swing.JTextField();
        jTextFieldFSW2 = new javax.swing.JTextField();
        jTextFieldRSW3 = new javax.swing.JTextField();
        jTextFieldFSW3 = new javax.swing.JTextField();
        jTextFieldSobraInicial = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldCSW2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxTurn = new javax.swing.JComboBox<>();
        jTextFieldNameSW = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButtonBackSW = new javax.swing.JButton();
        jButtonNextSW = new javax.swing.JButton();
        jLabelCanastasCom = new javax.swing.JLabel();
        jLabelCanastasIncom = new javax.swing.JLabel();
        jLabel212 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jTextFieldSSW4 = new javax.swing.JTextField();
        jButtonDAS = new javax.swing.JButton();
        jTextFieldCodeSW = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldTotalScrap = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btnStop = new javax.swing.JButton();
        jTextFieldCantMOG = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(900, 1600));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1610, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(900, 1600));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Fecha:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 120, 57));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 250, 70));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Nombre:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, 45));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Hora inicio:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 295, -1, 46));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Hora fin:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(418, 295, -1, -1));

        jLabelTotal_Hours.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jLabelTotal_Hours.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTotal_Hours.setText("Horas trabajadas:");
        getContentPane().add(jLabelTotal_Hours, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 359, -1, 50));

        jLabelPiezasxfila.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jLabelPiezasxfila.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPiezasxfila.setText("Piezas x Fila");
        getContentPane().add(jLabelPiezasxfila, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 570, 180, -1));

        jTextFieldCantSW1.setBackground(new java.awt.Color(255, 255, 0));
        jTextFieldCantSW1.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jTextFieldCantSW1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(jTextFieldCantSW1, new org.netbeans.lib.awtextra.AbsoluteConstraints(664, 616, 172, 110));

        jTextFieldRSW1.setBackground(new java.awt.Color(255, 255, 0));
        jTextFieldRSW1.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jTextFieldRSW1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(jTextFieldRSW1, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 616, 180, 110));

        jLabel19.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jLabel19.setText("Total de piezas recibidas:");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 1359, -1, -1));

        jTextFieldTPiecesSW.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldTPiecesSW.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        getContentPane().add(jTextFieldTPiecesSW, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 1360, 254, 51));

        jTextFieldStartSW.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldStartSW.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        getContentPane().add(jTextFieldStartSW, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 295, 191, 46));

        jTextFieldEndSW.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldEndSW.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        getContentPane().add(jTextFieldEndSW, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 290, 191, 46));

        jTextFieldTotalSW.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldTotalSW.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        jTextFieldTotalSW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTotalSWActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldTotalSW, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, 300, 50));

        jDateChooserDateSW.setBackground(new java.awt.Color(255, 255, 0));
        jDateChooserDateSW.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        jDateChooserDateSW.setPreferredSize(new java.awt.Dimension(100, 40));
        getContentPane().add(jDateChooserDateSW, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 564, 57));

        jTextFieldFSW1.setBackground(new java.awt.Color(255, 255, 0));
        jTextFieldFSW1.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jTextFieldFSW1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(jTextFieldFSW1, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 616, 180, 110));

        jTextFieldCSW1.setBackground(new java.awt.Color(255, 255, 0));
        jTextFieldCSW1.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jTextFieldCSW1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(jTextFieldCSW1, new org.netbeans.lib.awtextra.AbsoluteConstraints(466, 616, 180, 110));

        jTextFieldRSW2.setEditable(false);
        jTextFieldRSW2.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldRSW2.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jTextFieldRSW2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(jTextFieldRSW2, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 872, 180, 110));

        jTextFieldFSW2.setEditable(false);
        jTextFieldFSW2.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldFSW2.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jTextFieldFSW2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(jTextFieldFSW2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 870, 180, 110));

        jTextFieldRSW3.setEditable(false);
        jTextFieldRSW3.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldRSW3.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jTextFieldRSW3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(jTextFieldRSW3, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 1141, 180, 110));

        jTextFieldFSW3.setBackground(new java.awt.Color(255, 255, 0));
        jTextFieldFSW3.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jTextFieldFSW3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(jTextFieldFSW3, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 1141, 180, 110));

        jTextFieldSobraInicial.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldSobraInicial.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jTextFieldSobraInicial.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldSobraInicial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldSobraInicialKeyTyped(evt);
            }
        });
        getContentPane().add(jTextFieldSobraInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 430, 200, 60));

        jLabel11.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Canastas");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(664, 570, 172, -1));

        jTextFieldCSW2.setBackground(new java.awt.Color(255, 255, 0));
        jTextFieldCSW2.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jTextFieldCSW2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(jTextFieldCSW2, new org.netbeans.lib.awtextra.AbsoluteConstraints(466, 872, 180, 110));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Scrap total:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 440, 160, -1));

        jComboBoxTurn.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jComboBoxTurn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona", "1", "2", "3" }));
        getContentPane().add(jComboBoxTurn, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 440, -1, -1));

        jTextFieldNameSW.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldNameSW.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        getContentPane().add(jTextFieldNameSW, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 564, 45));

        jLabel9.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Filas");
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 570, 180, -1));

        jLabel10.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 360, 200, 60));

        jLabel14.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 1000, 180, 130));

        jLabel12.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(466, 792, 180, 67));

        jLabel13.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 792, 180, 70));

        jLabel17.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Filas");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 792, 180, 67));

        jLabel16.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 1000, 180, 130));

        jLabel15.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Sobrante");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(466, 1000, 180, 130));

        jButtonBackSW.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/salirr.png"))); // NOI18N
        jButtonBackSW.setBorderPainted(false);
        jButtonBackSW.setContentAreaFilled(false);
        getContentPane().add(jButtonBackSW, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 1440, 262, 71));

        jButtonNextSW.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/siguente.png"))); // NOI18N
        jButtonNextSW.setBorderPainted(false);
        jButtonNextSW.setContentAreaFilled(false);
        getContentPane().add(jButtonNextSW, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 1440, 250, -1));

        jLabelCanastasCom.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jLabelCanastasCom.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCanastasCom.setText("Canastas Completas");
        jLabelCanastasCom.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabelCanastasCom, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 522, 822, -1));

        jLabelCanastasIncom.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jLabelCanastasIncom.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCanastasIncom.setText("Canastas Incompletas");
        jLabelCanastasIncom.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabelCanastasIncom, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 744, 819, -1));

        jLabel212.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jLabel212.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel212.setText("Niveles");
        getContentPane().add(jLabel212, new org.netbeans.lib.awtextra.AbsoluteConstraints(466, 570, 180, -1));

        jLabel22.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Niveles");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(466, 570, 180, -1));

        jTextFieldSSW4.setBackground(new java.awt.Color(255, 255, 0));
        jTextFieldSSW4.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jTextFieldSSW4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(jTextFieldSSW4, new org.netbeans.lib.awtextra.AbsoluteConstraints(465, 1141, 180, 110));

        jButtonDAS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/DASSECOND.png"))); // NOI18N
        jButtonDAS.setToolTipText("");
        jButtonDAS.setBorderPainted(false);
        jButtonDAS.setContentAreaFilled(false);
        getContentPane().add(jButtonDAS, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 1080, 170, 80));

        jTextFieldCodeSW.setBackground(new java.awt.Color(255, 255, 0));
        jTextFieldCodeSW.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        getContentPane().add(jTextFieldCodeSW, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, 410, 50));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Turno:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 110, -1));

        jTextFieldTotalScrap.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldTotalScrap.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jTextFieldTotalScrap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTotalScrapActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldTotalScrap, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 430, 120, 60));

        jLabel8.setText(Global.VERSION);
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 10, 70, -1));

        btnStop.setForeground(new java.awt.Color(255, 255, 255));
        btnStop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/PARO.png"))); // NOI18N
        btnStop.setBorderPainted(false);
        btnStop.setContentAreaFilled(false);
        getContentPane().add(btnStop, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 1190, 170, 80));

        jTextFieldCantMOG.setBackground(new java.awt.Color(255, 255, 0));
        jTextFieldCantMOG.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jTextFieldCantMOG.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(jTextFieldCantMOG, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 1360, 190, 50));

        jLabel18.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Cambio MOG");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 1260, 240, 130));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldTotalSWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTotalSWActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTotalSWActionPerformed

    private void jTextFieldSobraInicialKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSobraInicialKeyTyped
        // TODO add your handling code here:
        char caracter = evt.getKeyChar();
            if(jTextFieldSobraInicial.getText().length()==4){
                evt.consume();
            }
    }//GEN-LAST:event_jTextFieldSobraInicialKeyTyped

    private void jTextFieldTotalScrapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTotalScrapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTotalScrapActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Second_windowRBP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Second_windowRBP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Second_windowRBP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Second_windowRBP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Second_windowRBP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnStop;
    private javax.swing.ButtonGroup buttonGroup1;
    public javax.swing.JButton jButtonBackSW;
    public javax.swing.JButton jButtonDAS;
    public javax.swing.JButton jButtonNextSW;
    public javax.swing.JComboBox<String> jComboBoxTurn;
    public com.toedter.calendar.JDateChooser jDateChooserDateSW;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel10;
    public javax.swing.JLabel jLabel11;
    public javax.swing.JLabel jLabel12;
    public javax.swing.JLabel jLabel13;
    public javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    public javax.swing.JLabel jLabel16;
    public javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel212;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    public javax.swing.JLabel jLabel9;
    public javax.swing.JLabel jLabelCanastasCom;
    public javax.swing.JLabel jLabelCanastasIncom;
    public javax.swing.JLabel jLabelPiezasxfila;
    public javax.swing.JLabel jLabelTotal_Hours;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JTextField jTextFieldCSW1;
    public javax.swing.JTextField jTextFieldCSW2;
    public javax.swing.JTextField jTextFieldCantMOG;
    public javax.swing.JTextField jTextFieldCantSW1;
    public javax.swing.JPasswordField jTextFieldCodeSW;
    public javax.swing.JTextField jTextFieldEndSW;
    public javax.swing.JTextField jTextFieldFSW1;
    public javax.swing.JTextField jTextFieldFSW2;
    public javax.swing.JTextField jTextFieldFSW3;
    public javax.swing.JTextField jTextFieldNameSW;
    public javax.swing.JTextField jTextFieldRSW1;
    public javax.swing.JTextField jTextFieldRSW2;
    public javax.swing.JTextField jTextFieldRSW3;
    public javax.swing.JTextField jTextFieldSSW4;
    public javax.swing.JTextField jTextFieldSobraInicial;
    public javax.swing.JTextField jTextFieldStartSW;
    public javax.swing.JTextField jTextFieldTPiecesSW;
    public javax.swing.JTextField jTextFieldTotalSW;
    public javax.swing.JTextField jTextFieldTotalScrap;
    // End of variables declaration//GEN-END:variables
}
