/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author DMM-ADMIN
 */
public class view_report_half extends javax.swing.JFrame {

    /**
     * Creates new form view_report_half
     */
    public view_report_half() {
        initComponents();
        setLocationRelativeTo(null); 
        setTitle("Reporte DAS");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupHB = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableReporteDas = new javax.swing.JTable();
        jDateChooserInicio = new com.toedter.calendar.JDateChooser();
        jDateChooserFin = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jButtonBuscarDas = new javax.swing.JButton();
        jButtonExportarDas = new javax.swing.JButton();
        jButtonBack_HB = new javax.swing.JButton();
        jCheckBoxPrensa = new javax.swing.JCheckBox();
        jCheckBoxMaq = new javax.swing.JCheckBox();
        jCheckBoxPlat = new javax.swing.JCheckBox();
        jCheckBoxPCK = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldMOG = new javax.swing.JTextField();
        jComboBoxProce = new javax.swing.JComboBox<>();
        jButtonBuscarDasxMOG = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(937, 635));
        setMinimumSize(new java.awt.Dimension(937, 635));
        setPreferredSize(new java.awt.Dimension(937, 635));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableReporteDas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableReporteDas.setName(""); // NOI18N
        jScrollPane1.setViewportView(jTableReporteDas);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 830, 350));
        getContentPane().add(jDateChooserInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 200, -1));
        getContentPane().add(jDateChooserFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 40, 200, -1));

        jLabel1.setText("Version 28-07-21");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 10, -1, -1));

        jButtonBuscarDas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonBuscarDas.setText("BUSCAR");
        getContentPane().add(jButtonBuscarDas, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 50, 90, -1));

        jButtonExportarDas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonExportarDas.setText("Exportar");
        getContentPane().add(jButtonExportarDas, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 100, -1, -1));

        jButtonBack_HB.setText("Regresar");
        getContentPane().add(jButtonBack_HB, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 660, -1, -1));

        buttonGroupHB.add(jCheckBoxPrensa);
        jCheckBoxPrensa.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jCheckBoxPrensa.setText("PRENSA");
        jCheckBoxPrensa.setToolTipText("");
        getContentPane().add(jCheckBoxPrensa, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, -1));

        buttonGroupHB.add(jCheckBoxMaq);
        jCheckBoxMaq.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jCheckBoxMaq.setText("MAQUINADO");
        getContentPane().add(jCheckBoxMaq, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, -1, -1));

        buttonGroupHB.add(jCheckBoxPlat);
        jCheckBoxPlat.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jCheckBoxPlat.setText("PLATINADO");
        getContentPane().add(jCheckBoxPlat, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, -1, -1));

        buttonGroupHB.add(jCheckBoxPCK);
        jCheckBoxPCK.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jCheckBoxPCK.setText("EMPAQUE");
        getContentPane().add(jCheckBoxPCK, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 110, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setText("Búsqueda por MOG");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 1000, 10));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("*Colocar sólo los ultimos 5 dígitos*");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("MOG:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, -1, -1));

        jTextFieldMOG.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextFieldMOG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMOGActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldMOG, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, 160, -1));

        jComboBoxProce.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jComboBoxProce.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona el proceso", "Prensa", "Maquinado", "Platinado", "Empaque" }));
        getContentPane().add(jComboBoxProce, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 210, -1, -1));

        jButtonBuscarDasxMOG.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonBuscarDasxMOG.setText("BUSCAR");
        getContentPane().add(jButtonBuscarDasxMOG, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 210, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldMOGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMOGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMOGActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(view_report_half.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(view_report_half.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(view_report_half.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(view_report_half.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new view_report_half().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.ButtonGroup buttonGroupHB;
    public javax.swing.JButton jButtonBack_HB;
    public javax.swing.JButton jButtonBuscarDas;
    public javax.swing.JButton jButtonBuscarDasxMOG;
    public javax.swing.JButton jButtonExportarDas;
    public javax.swing.JCheckBox jCheckBoxMaq;
    public javax.swing.JCheckBox jCheckBoxPCK;
    public javax.swing.JCheckBox jCheckBoxPlat;
    public javax.swing.JCheckBox jCheckBoxPrensa;
    public javax.swing.JComboBox<String> jComboBoxProce;
    public com.toedter.calendar.JDateChooser jDateChooserFin;
    public com.toedter.calendar.JDateChooser jDateChooserInicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JTable jTableReporteDas;
    public javax.swing.JTextField jTextFieldMOG;
    // End of variables declaration//GEN-END:variables

    
}
